#pragma once
enum CORE_SHADER_TYPE
{
    SHADER_TYPE_UNUSED = 0,
    SHADER_TYPE_VERTEX = 1,
    SHADER_TYPE_PIXEL = 2,
    SHADER_TYPE_HULL = 3,
    SHADER_TYPE_COMPUTE = 4
};

enum CORE_SHADER_INPUT_TYPE
{
    SHADER_INPUT_UNUSED         = 0,
    SHADER_INPUT_PER_VERTEX     = 1,
    SHADER_INPUT_PER_INSTANCE   = 2
};